baseURL = "https://medecinelibre.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
title = "Médecine Libre"

enableEmoji = true
metaDataFormat = "yaml"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/freemedsoft/hugo/edit/master/content/"
  # Author of the site, will be used in meta information
  author = "Jérôme Pinguet"
  # Description of the site, will be used in meta information
  description = "FreeMedSoft, open source healthcare technology."
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"


[Languages]                                                                  
[Languages.en]                
title = "Médecine Libre"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-blogger'></i> Blog"
url = "https://medecinelibre.com/blog"
weight = 25

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-users'></i> About"
url = "/about"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-dollar'></i> COI"
url = "/coi"
weight = 35

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-phone'></i> Phone"
url = "/phone"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> @medecinelibre"
url = "https://twitter.com/medecinelibre"
weight = 50

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 60
                                                           
[Languages.fr]                             
title = "Médecine Libre"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-users'></i> A propos"
url = "/about"
weight = 30

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-dollar'></i> DPI"
url = "/coi"
weight = 35

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-phone'></i> Téléphone"
url = "/phone"
weight = 40


[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> @medecinelibre"
url = "https://twitter.com/medecinelibre"
weight = 50

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 60

[Languages.tr]
title = "Médecine Libre"
weight = 3
languageName = "Türkçe"


[[Languages.tr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-users'></i> Hakkımızda"
url = "/about"
weight = 30

[[Languages.tr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-phone'></i> Telefon"
url = "/phone"
weight = 40

[[Languages.tr.menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> @medecinelibre"
url = "https://twitter.com/medecinelibre"
weight = 50

[[Languages.tr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 60
